Models/Document.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace OrgDocs.Models
{
    public class Document
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Last Update")]
        public DateTime LastUpdate { get; set; }
        [Display(Name = "Category")]
        public int CategoryId { get; set; }
        [ForeignKey("CategoryId")]
        public Category Category { get; set; }
        [Display(Name = "Dept")]
        public int DeptId { get; set;}
        [ForeignKey("DeptId")]
        public Dept Dept { get; set; }

        [Display(Name ="Document")]
        public string PdfUrl { get; set; }
        
        public ICollection<Subscription> Subscriptions { get; set; }
    }
}

Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OrgDocs.Data;
using OrgDocs.Models;
using OrgDocs.Utility;

namespace OrgDocs.Controllers
{
    public class DocumentsController : Controller
    {
        private readonly OrgDocsContext _context;
        public readonly IWebHostEnvironment _hostEnvironment;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IEmailSender _emailSender;

        public DocumentsController(OrgDocsContext context, IWebHostEnvironment hostEnvironment, UserManager<IdentityUser> userManager, 
            IEmailSender emailSender)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
            _userManager = userManager;
            _emailSender = emailSender;
        }

        // GET: Documents
        public async Task<IActionResult> Index(
            string sortOrder,
            string currentFilter,
            string catFilter,
            string deptFilter,
            string searchString,
            int? pageNumber)
        {

            ViewData["CurrentSort"] = sortOrder;
            ViewData["TitleSortParam"] = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewData["LastUpdateSortParam"] = sortOrder == "LastUpdate" ? "last_update_desc" : "LastUpdate";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            ViewData["DeptFilter"] = deptFilter;
            ViewData["CatFilter"] = catFilter;
            ViewData["UserID"] = User.FindFirstValue(ClaimTypes.NameIdentifier);

            //get list of Categories
            IQueryable<string> catQuery = from category in _context.Categories orderby category.Name select category.Name;


            //get list of depts
            IQueryable<string> deptQuery = from dept in _context.Depts orderby dept.Department select dept.Department;

            //get documents
            var documents = from document in _context.Documents
                            .Include(d => d.Category)
                            .Include(d => d.Dept)
                            .Include(d=> d.Subscriptions)
                            select document;



            //filter logic

            if (!String.IsNullOrEmpty(searchString))
            {
                documents = documents.Where(document => document.Title.Contains(searchString));

            }

            if (!String.IsNullOrEmpty(catFilter))
            {
                documents = documents.Where(document => document.Category.Name.Contains(catFilter));
            }

            if (!String.IsNullOrEmpty(deptFilter))
            {
                documents = documents.Where(document => document.Dept.Department.Contains(deptFilter));
            }




            //sort logic

            switch (sortOrder)
            {
                case "title_desc":
                    documents = documents.OrderByDescending(d => d.Title);
                    break;
                case "LastUpdate":
                    documents = documents.OrderBy(d => d.LastUpdate);
                    break;
                case "last_update_desc":
                    documents = documents.OrderByDescending(d => d.LastUpdate);
                    break;
                default:
                    documents = documents.OrderBy(d => d.Title);
                    break;
            }



            //pagination logic
            int pageSize = 3;
            var docFiltersVM = new DocFiltersVM
            {
                Categories = new SelectList(await catQuery.ToListAsync(), catFilter),
                Depts = new SelectList(await deptQuery.ToListAsync(), deptFilter),
                Documents = await PaginatedList<Document>.CreateAsync(
                    documents.AsNoTracking(), pageNumber ?? 1, pageSize),

            };

            return View(docFiltersVM);
        }

        // GET: Documents/Details/5

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = await _context.Documents
                .Include(d => d.Category)
                .Include(d => d.Dept)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (document == null)
            {
                return NotFound();
            }

            return View(document);
        }

        // GET: Documents/Create
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["DeptId"] = new SelectList(_context.Depts, "Id", "Department");
            return View();
        }

        // POST: Documents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = SD.Role_Admin)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,LastUpdate,CategoryId,DeptId")] Document document)
        {
            document.LastUpdate = DateTime.Now;
            if (ModelState.IsValid)
            {

                string webRootPath = _hostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                if (files.Count > 0)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(webRootPath, @"documents\uploads");
                    var extension = Path.GetExtension(files[0].FileName);
                    long size = files[0].Length;

                    if (extension != ".pdf")  //not processing request if it is not a pdf
                    {
                        ModelState.AddModelError(string.Empty, "Error: this filetype is not allowed");
                        return View(document);
                    }

                    if (size > 2000000)  //not processing request if size is bigger than 2mb
                    {
                        ModelState.AddModelError(string.Empty, "Error: File size larger than 2 MB");
                        return View(document);
                    }

                    using (FileStream fileStreams = new FileStream(Path.Combine(uploads, fileName + extension),
                        FileMode.Create))
                    {
                        files[0].CopyTo(fileStreams);
                    }
                    document.PdfUrl = @"\documents\uploads\" + fileName + extension;
                }


                _context.Add(document);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", document.CategoryId);
            ViewData["DeptId"] = new SelectList(_context.Depts, "Id", "Department", document.DeptId);
            return View(document);
        }

        // GET: Documents/Edit/5
        [Authorize(Roles = SD.Role_Admin)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = await _context.Documents.FindAsync(id);
            if (document == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", document.CategoryId);
            ViewData["DeptId"] = new SelectList(_context.Depts, "Id", "Department", document.DeptId);
            return View(document);
        }


        [Authorize(Roles = SD.Role_Admin)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,LastUpdate,CategoryId,DeptId,PdfUrl")] Document document)
        {
            if (id != document.Id)
            {
                return NotFound();
            }

            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", document.CategoryId);
            ViewData["DeptId"] = new SelectList(_context.Depts, "Id", "Department", document.DeptId);

            if (ModelState.IsValid)
            {
                string webRootPath = _hostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                bool uploadedNewFile = false;
                long size = files[0].Length;

                if (files.Count > 0) //a new file has been uploded in edit
                {
                    uploadedNewFile = true;
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(webRootPath, @"documents\uploads");
                    var extension = Path.GetExtension(files[0].FileName);
                    var pdfPath = Path.Combine(webRootPath, document.PdfUrl.TrimStart('\\'));

                    if (extension != ".pdf")  //not processing request if it is not a pdf
                    {

                        ModelState.AddModelError(string.Empty, "Error: this filetype is not allowed");
                        return View(document);
                    }

                    if (size > 2000000)  //not processing request if size is bigger than 2mb
                    {

Views/Documents/Create.cshtml
@model OrgDocs.Models.Document

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Document</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="DeptId" class="control-label"></label>
                <select asp-for="DeptId" class="form-control" asp-items="ViewBag.DeptId"></select>
            </div>
            <div class="form-group">
                <label class="control-label"> Upload Document (PDF only)</label>
                <input type="file" name="files" id="uploadBox" multiple class="form-control" />
                <span asp-validation-for="PdfUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"><i style="font-size:1.5em" class="far fa-arrow-alt-circle-left"></i></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Documents/Delete.cshtml
@model OrgDocs.Models.Document

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Document</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastUpdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastUpdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dept)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dept.Department)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index"><i style="font-size:1.5em" class="far fa-arrow-alt-circle-left"></i></a>
    </form>
</div>

Views/Documents/Details.cshtml
@model OrgDocs.Models.Document

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Document</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastUpdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastUpdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dept)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dept.Department)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id"><i style="font-size:1.5em" class="far fa-edit"></i></a> |
    <a asp-action="Index"><i style="font-size:1.5em" class="far fa-arrow-alt-circle-left"></i></a>
</div>

Views/Documents/Edit.cshtml
@model OrgDocs.Models.Document

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Edit Document</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeptId" class="control-label"></label>
                <select asp-for="DeptId" class="form-control" asp-items="ViewBag.DeptId"></select>
                <span asp-validation-for="DeptId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label"> Upload New Document (PDF only)</label>
                <input type="file" name="files" id="uploadBox" multiple class="form-control" />
                <input type="hidden" asp-for="PdfUrl" />
                <span asp-validation-for="PdfUrl" class="text-danger"></span>
           
     
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"><i style="font-size:1.5em" class="far fa-arrow-alt-circle-left"></i></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Documents/Index.cshtml
@model OrgDocs.Models.DocFiltersVM
@using OrgDocs.Utility

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h4 class="text-center">Documentations</h4>

@if (this.User.IsInRole(SD.Role_Admin))
{
<p class="text-right">
    <a class="btn btn-outline-light" asp-action="Create">Add New Document</a>
</p>
}

<form asp-controller="Documents" asp-action="Index" method="get" class="form-group">
    <p>
        <div class="row">
            <div class="col">
                <select class="form-control" name="catFilter" asp-items="Model.Categories">
                    <option value="">All Categories</option>
                </select>
            </div>
            <div class="col">
                <select class="form-control" name="deptFilter" asp-items="Model.Depts">
                    <option value="">All Depts</option>
                </select>
            </div>
            <div class="col">
                <input class="form-control" placeholder="Title" type="text" value="@ViewData["CurrentFilter"]" name="SearchString" />
            </div>
            <div class="col">
                <input class="btn btn-primary" type="submit" value="Filter" />
            </div>
        </div>


    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>

                <a asp-action="Index" asp-route-sortOrder="@ViewData["TitleSortParam"]"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   asp-route-deptFilter="@ViewData["DeptFilter"]"
                   asp-route-catFilter="@ViewData["CatFilter"]">
                    Title
                </a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["LastUpdateSortParam"]"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   asp-route-deptFilter="@ViewData["DeptFilter"]"
                   asp-route-catFilter="@ViewData["CatFilter"]">
                    Last Update
                </a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Documents[0].Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Documents[0].Dept)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Documents[0].PdfUrl)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Documents)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastUpdate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dept.Department)
                </td>
                <td>
                    <a target="_blank" href="@Html.DisplayFor(modelItem => item.PdfUrl)">View Document</a>
                </td>
                <td>
                    <div class="row">


                        @if (this.User.IsInRole(SD.Role_Admin))
                        {
                            <div class="col">
                                <a asp-action="Details" asp-route-id="@item.Id"><i class="fas fa-info"></i></a>
                            </div>
                            <div class="col">
                                <a asp-action="Delete" asp-route-id="@item.Id"><i class="far fa-trash-alt"></i></a>
                            </div>
                            <div class="col">
                                <a asp-action="Edit" asp-route-id="@item.Id"><i class="far fa-edit"></i></a>
                            </div>
                        }
                        @if(this.User.IsInRole(SD.Role_Admin) || this.User.IsInRole(SD.Role_Employee))
                        { 
                            <div class="col">

                                <form asp-action="Subscribe">
                                    <input name="documentID" value="@item.Id" hidden />
                                    <input name="userID" value="@ViewData["UserID"]" hidden />
                                    @if (item.Subscriptions.Count(item => item.ApplicationUserID == (string)(ViewData["UserID"])) > 0)
                                    {

                                        <button style="width:91.6px" class="btn btn-sm btn-outline-danger btn-sub" type="submit">Unsubscribe</button>

                                    }
                                    else
                                    {



                                        <button style="width:91.6px" class="btn btn-sm btn-outline-light btn-sub" type="submit">Subscribe</button>

                                    }
                                </form>
                                </div>
                        }
                    </div>


                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.Documents.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.Documents.HasNextPage ? "disabled" : "";

}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.Documents.PageIndex -1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   asp-route-deptFilter="@ViewData["DeptFilter"]"
   asp-route-catFilter="@ViewData["CatFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.Documents.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   asp-route-deptFilter="@ViewData["DeptFilter"]"
   asp-route-catFilter="@ViewData["CatFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>